name: unidist
channels:
  - conda-forge
dependencies:
  # for development
  - cloudpickle
  - dask>=2.22.0
  - distributed>=2.22.0
  - mpi4py>=3.0.3
  - msgpack-python>=1.0.0
  - packaging
  - psutil
  - pytest
  - ray-default>=1.4.0
  # workaround for https://github.com/conda/conda/issues/11744
  - grpcio!=1.45.*
  - grpcio!=1.46.*
  # for downloading packages from PyPI
  - pip
  - pip:
      # for building the documentation
      - sphinx
      - sphinx_rtd_theme
      # for code checks
      - black
      - flake8
